name: flutter_base_template
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  app_settings: ^5.1.1
  email_validator: ^2.1.17
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  go_router: ^12.1.3
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.3
  sentry_flutter: ^7.13.2
  shared_preferences: ^2.2.2
  oauth2: ^2.0.2
  local_auth: ^2.1.7
  flutter_secure_storage: ^9.0.0
  gap: ^3.0.1
  mockito: ^5.4.4
  http: ^1.1.2
  matomo_tracker: ^4.1.1
  flutter_animate: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  riverpod_lint: ^2.3.7
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  test: ^1.24.9

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/